### ISSUE TITLE
When no `root` specified, all files have been uploaded to the folder named `/`

### ISSUE THREAD

**Issue by godruoyi** [syhily/astro-uploader#1]
## Description

First of all, thank you for creating this. I'm using it to upload all my pictures to R2, which is awesome. However, I've encountered a small issue. When I didn't set the `root` option, all the images were uploaded to a folder named "/". Ideally, they should be uploaded directly to the root directory.

here are my config:

```
uploader({
    paths: ['assets'],
    endpoint: process.env.S3_ENDPOINT,
    bucket: process.env.S3_BUCKET,
    accessKey: process.env.S3_ACCESS_KEY,
    secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
}),
```

the result: 
![CleanShot 2024-06-28 at 17 40 26@2x](https://github.com/syhily/astro-uploader/assets/16079222/51a470c9-9239-4f04-a4b2-39e8b91c4c1b)

If I understand correctly, there should be an `assets` folder in the root directory, right?

**Comment by syhily** [comment]
Thanks for submitting this issue. I'll check it later today. Different S3 compatible storage may have different logic in handling the path start with slash.

**Comment by syhily** [comment]
The issue has been fixed and tested on Cloudflare R2. Thanks for reporting this. You can bump the version to `1.0.3`.
